// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using X39.UnitedTacticalForces.WebApp.Api.ResourceClaim.Item.Item.Users.Item.Add.Item;
namespace X39.UnitedTacticalForces.WebApp.Api.ResourceClaim.Item.Item.Users.Item.Add
{
    /// <summary>
    /// Builds and executes requests for operations under \resource-claim\{resourcePrefix}\{resourceIdentifier}\users\{userId}\add
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AddRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the X39.UnitedTacticalForces.WebApp.Api.resourceClaim.item.item.users.item.add.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::X39.UnitedTacticalForces.WebApp.Api.ResourceClaim.Item.Item.Users.Item.Add.Item.WithResourceClaimItemRequestBuilder"/></returns>
        public global::X39.UnitedTacticalForces.WebApp.Api.ResourceClaim.Item.Item.Users.Item.Add.Item.WithResourceClaimItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("resourceClaim", position);
                return new global::X39.UnitedTacticalForces.WebApp.Api.ResourceClaim.Item.Item.Users.Item.Add.Item.WithResourceClaimItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.ResourceClaim.Item.Item.Users.Item.Add.AddRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AddRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/resource-claim/{resourcePrefix}/{resourceIdentifier}/users/{userId}/add", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.ResourceClaim.Item.Item.Users.Item.Add.AddRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AddRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/resource-claim/{resourcePrefix}/{resourceIdentifier}/users/{userId}/add", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
