// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using X39.UnitedTacticalForces.WebApp.Api.Events.Item.Slotting.Item.Unassign.User;
namespace X39.UnitedTacticalForces.WebApp.Api.Events.Item.Slotting.Item.Unassign
{
    /// <summary>
    /// Builds and executes requests for operations under \events\{eventId}\slotting\{slotNumber}\unassign
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UnassignRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The user property</summary>
        public global::X39.UnitedTacticalForces.WebApp.Api.Events.Item.Slotting.Item.Unassign.User.UserRequestBuilder User
        {
            get => new global::X39.UnitedTacticalForces.WebApp.Api.Events.Item.Slotting.Item.Unassign.User.UserRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.Events.Item.Slotting.Item.Unassign.UnassignRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UnassignRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/events/{eventId}/slotting/{slotNumber}/unassign", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.Events.Item.Slotting.Item.Unassign.UnassignRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UnassignRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/events/{eventId}/slotting/{slotNumber}/unassign", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
