// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using X39.UnitedTacticalForces.WebApp.Api.Models;
using X39.UnitedTacticalForces.WebApp.Api.Wiki.Item.Revisions.Header;
using X39.UnitedTacticalForces.WebApp.Api.Wiki.Item.Revisions.Item;
namespace X39.UnitedTacticalForces.WebApp.Api.Wiki.Item.Revisions
{
    /// <summary>
    /// Builds and executes requests for operations under \wiki\{pageKey}\revisions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RevisionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The header property</summary>
        public global::X39.UnitedTacticalForces.WebApp.Api.Wiki.Item.Revisions.Header.HeaderRequestBuilder Header
        {
            get => new global::X39.UnitedTacticalForces.WebApp.Api.Wiki.Item.Revisions.Header.HeaderRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the X39.UnitedTacticalForces.WebApp.Api.wiki.item.revisions.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::X39.UnitedTacticalForces.WebApp.Api.Wiki.Item.Revisions.Item.WithRevisionKeyItemRequestBuilder"/></returns>
        public global::X39.UnitedTacticalForces.WebApp.Api.Wiki.Item.Revisions.Item.WithRevisionKeyItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("revisionKey", position);
                return new global::X39.UnitedTacticalForces.WebApp.Api.Wiki.Item.Revisions.Item.WithRevisionKeyItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the X39.UnitedTacticalForces.WebApp.Api.wiki.item.revisions.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::X39.UnitedTacticalForces.WebApp.Api.Wiki.Item.Revisions.Item.WithRevisionKeyItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::X39.UnitedTacticalForces.WebApp.Api.Wiki.Item.Revisions.Item.WithRevisionKeyItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("revisionKey", position);
                return new global::X39.UnitedTacticalForces.WebApp.Api.Wiki.Item.Revisions.Item.WithRevisionKeyItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.Wiki.Item.Revisions.RevisionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RevisionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/wiki/{pageKey}/revisions", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.Wiki.Item.Revisions.RevisionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RevisionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/wiki/{pageKey}/revisions", rawUrl)
        {
        }
        /// <returns>A <see cref="global::X39.UnitedTacticalForces.WebApp.Api.Models.WikiPageRevisionDto"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::X39.UnitedTacticalForces.WebApp.Api.Models.WikiPageRevisionDto?> PostAsync(global::X39.UnitedTacticalForces.WebApp.Api.Wiki.Item.Revisions.RevisionsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::X39.UnitedTacticalForces.WebApp.Api.Models.WikiPageRevisionDto> PostAsync(global::X39.UnitedTacticalForces.WebApp.Api.Wiki.Item.Revisions.RevisionsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::X39.UnitedTacticalForces.WebApp.Api.Models.WikiPageRevisionDto>(requestInfo, global::X39.UnitedTacticalForces.WebApp.Api.Models.WikiPageRevisionDto.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::X39.UnitedTacticalForces.WebApp.Api.Wiki.Item.Revisions.RevisionsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::X39.UnitedTacticalForces.WebApp.Api.Wiki.Item.Revisions.RevisionsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json, text/plain;q=0.9");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/x-www-form-urlencoded", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::X39.UnitedTacticalForces.WebApp.Api.Wiki.Item.Revisions.RevisionsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::X39.UnitedTacticalForces.WebApp.Api.Wiki.Item.Revisions.RevisionsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::X39.UnitedTacticalForces.WebApp.Api.Wiki.Item.Revisions.RevisionsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RevisionsRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
