//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace X39.UnitedTacticalForces.Api.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("X39.UnitedTacticalForces.Api.Properties.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string ServerController_Arma3_BasicCfg_GeneralGroup {
            get {
                return ResourceManager.GetString("ServerController_Arma3_BasicCfg_GeneralGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        internal static string ServerController_Arma3_Host {
            get {
                return ResourceManager.GetString("ServerController_Arma3_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port on which the dedicated server should listen..
        /// </summary>
        internal static string ServerController_Arma3_Host_Port_Description {
            get {
                return ResourceManager.GetString("ServerController_Arma3_Host_Port_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string ServerController_Arma3_Host_Port_Title {
            get {
                return ResourceManager.GetString("ServerController_Arma3_Host_Port_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loads the specified subfolders for various server-side (not transferred to clients) mods. Separated by semicolons. Absolute path and multiple stacked folders are possible.
        ///In Linux, arguments for multiple folders require the following separator syntax: -mod=mod1\;mod2\;mod3..
        /// </summary>
        internal static string ServerController_Arma3_Host_ServerMod_Description {
            get {
                return ResourceManager.GetString("ServerController_Arma3_Host_ServerMod_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server mods.
        /// </summary>
        internal static string ServerController_Arma3_Host_ServerMod_Title {
            get {
                return ResourceManager.GetString("ServerController_Arma3_Host_ServerMod_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of player uids (SteamID64) that are able to #login without providing a password..
        /// </summary>
        internal static string ServerController_Arma3_ServerCfg_Admins_Description {
            get {
                return ResourceManager.GetString("ServerController_Arma3_ServerCfg_Admins_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admins.
        /// </summary>
        internal static string ServerController_Arma3_ServerCfg_Admins_Title {
            get {
                return ResourceManager.GetString("ServerController_Arma3_ServerCfg_Admins_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of player Uids (SteamId64) that are allowed to ignore the rules of allowedFilePatching and verifySignatures so they can join the server with any mods of their choice.
        ///Signature errors are still logged by the server on connection and can kick the user if the error occurs before the server knows the client&apos;s SteamID, e.g. if they try to join with completely unsigned pbo&apos;s..
        /// </summary>
        internal static string ServerController_Arma3_ServerCfg_FilePatchingExceptions_Description {
            get {
                return ResourceManager.GetString("ServerController_Arma3_ServerCfg_FilePatchingExceptions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File patching exceptions.
        /// </summary>
        internal static string ServerController_Arma3_ServerCfg_FilePatchingExceptions_Title {
            get {
                return ResourceManager.GetString("ServerController_Arma3_ServerCfg_FilePatchingExceptions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string ServerController_Arma3_ServerCfg_GeneralGroup {
            get {
                return ResourceManager.GetString("ServerController_Arma3_ServerCfg_GeneralGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headless Client IPs. Im Falle mehrerer Headless Clients sind mehrere Verbindungen und Adressen zulässig..
        /// </summary>
        internal static string ServerController_Arma3_ServerCfg_HeadlessClients_Description {
            get {
                return ResourceManager.GetString("ServerController_Arma3_ServerCfg_HeadlessClients_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headless client IPs.
        /// </summary>
        internal static string ServerController_Arma3_ServerCfg_HeadlessClients_Title {
            get {
                return ResourceManager.GetString("ServerController_Arma3_ServerCfg_HeadlessClients_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server name visible in the game browser..
        /// </summary>
        internal static string ServerController_Arma3_ServerCfg_Hostname_Description {
            get {
                return ResourceManager.GetString("ServerController_Arma3_ServerCfg_Hostname_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servername.
        /// </summary>
        internal static string ServerController_Arma3_ServerCfg_Hostname_Title {
            get {
                return ResourceManager.GetString("ServerController_Arma3_ServerCfg_Hostname_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declares clients with unlimited bandwidth and almost no latency..
        /// </summary>
        internal static string ServerController_Arma3_ServerCfg_LocalClient_Description {
            get {
                return ResourceManager.GetString("ServerController_Arma3_ServerCfg_LocalClient_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local client IPs.
        /// </summary>
        internal static string ServerController_Arma3_ServerCfg_LocalClient_Title {
            get {
                return ResourceManager.GetString("ServerController_Arma3_ServerCfg_LocalClient_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bandwidth that is guaranteed never to be available to the server (in bps). This value helps the server estimate the available bandwidth..
        /// </summary>
        internal static string ServerController_Arma3_ServerCfg_MaxBandwidth_Description {
            get {
                return ResourceManager.GetString("ServerController_Arma3_ServerCfg_MaxBandwidth_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum bandwidth.
        /// </summary>
        internal static string ServerController_Arma3_ServerCfg_MaxBandwidth_Title {
            get {
                return ResourceManager.GetString("ServerController_Arma3_ServerCfg_MaxBandwidth_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users with a custom face or custom tone larger than this size will be rejected when attempting to connect..
        /// </summary>
        internal static string ServerController_Arma3_ServerCfg_MaxCustomFileSize_Description {
            get {
                return ResourceManager.GetString("ServerController_Arma3_ServerCfg_MaxCustomFileSize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum custom file size.
        /// </summary>
        internal static string ServerController_Arma3_ServerCfg_MaxCustomFileSize_Title {
            get {
                return ResourceManager.GetString("ServerController_Arma3_ServerCfg_MaxCustomFileSize_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of packets (grouped messages) that can be sent in one simulation cycle (&quot;frame&quot;). Increasing this value can reduce the delay on servers with high upload bandwidth..
        /// </summary>
        internal static string ServerController_Arma3_ServerCfg_MaxMsgSend_Description {
            get {
                return ResourceManager.GetString("ServerController_Arma3_ServerCfg_MaxMsgSend_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum messages per frame.
        /// </summary>
        internal static string ServerController_Arma3_ServerCfg_MaxMsgSend_Title {
            get {
                return ResourceManager.GetString("ServerController_Arma3_ServerCfg_MaxMsgSend_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of players that can connect to the server. The final number is the smaller value between the number given here and the number of mission slots..
        /// </summary>
        internal static string ServerController_Arma3_ServerCfg_MaxPlayers_Description {
            get {
                return ResourceManager.GetString("ServerController_Arma3_ServerCfg_MaxPlayers_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum players.
        /// </summary>
        internal static string ServerController_Arma3_ServerCfg_MaxPlayers_Title {
            get {
                return ResourceManager.GetString("ServerController_Arma3_ServerCfg_MaxPlayers_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum size (payload) of the guaranteed packet in bytes (without header). Small messages are packed into larger packets (aggregate messages). Guaranteed packets (aggregate messages) are used for non-recurring events like firing..
        /// </summary>
        internal static string ServerController_Arma3_ServerCfg_MaxSizeGuaranteed_Description {
            get {
                return ResourceManager.GetString("ServerController_Arma3_ServerCfg_MaxSizeGuaranteed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum TCP package size.
        /// </summary>
        internal static string ServerController_Arma3_ServerCfg_MaxSizeGuaranteed_Title {
            get {
                return ResourceManager.GetString("ServerController_Arma3_ServerCfg_MaxSizeGuaranteed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum size (payload) of the non-guaranteed packet in bytes (without header). Small messages are packed into larger packets (aggregate messages). Non-guaranteed packets (aggregate messages) are used for repetitive updates such as the position of soldiers or vehicles. Increasing this value can improve the bandwidth requirement, but may increase the delay..
        /// </summary>
        internal static string ServerController_Arma3_ServerCfg_MaxSizeNonguaranteed_Description {
            get {
                return ResourceManager.GetString("ServerController_Arma3_ServerCfg_MaxSizeNonguaranteed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum UDP package size.
        /// </summary>
        internal static string ServerController_Arma3_ServerCfg_MaxSizeNonguaranteed_Title {
            get {
                return ResourceManager.GetString("ServerController_Arma3_ServerCfg_MaxSizeNonguaranteed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bandwidth guaranteed to the server (in bps). This value helps the server estimate the available bandwidth. An overly optimistic value can increase delay and CPU load because too many messages are sent but discarded..
        /// </summary>
        internal static string ServerController_Arma3_ServerCfg_MinBandwidth_Description {
            get {
                return ResourceManager.GetString("ServerController_Arma3_ServerCfg_MinBandwidth_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected minimal bandwidth.
        /// </summary>
        internal static string ServerController_Arma3_ServerCfg_MinBandwidth_Title {
            get {
                return ResourceManager.GetString("ServerController_Arma3_ServerCfg_MinBandwidth_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal bug when sending updates over the network. Using a smaller value can cause units observed with binoculars or sniper rifles to move more smoothly, but this comes with increased network traffic.
        ///Example: A unit 1 km (distance d = 1 km) from the player with MinErrorToSend = 0.001 (METS = 0.001) would send an update if that unit moved 50 m (error value E = 50).
        ///Formula: d = sqrt[(20E)/METS] ; 1000 = sqrt[(20E)/0.001] -&gt; E = 50
        ///In reality, other factors of the object are also considered according to a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ServerController_Arma3_ServerCfg_MinErrorToSend_Description {
            get {
                return ResourceManager.GetString("ServerController_Arma3_ServerCfg_MinErrorToSend_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minmal error to send.
        /// </summary>
        internal static string ServerController_Arma3_ServerCfg_MinErrorToSend_Title {
            get {
                return ResourceManager.GetString("ServerController_Arma3_ServerCfg_MinErrorToSend_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal error when sending updates over the network for nearby units. Using a larger value may reduce traffic for nearby units. Also used to control traffic between client and server.
        ///Using MinErrorToSend alone, for small distance values (d), the frequency of high errors (E) would result in excessive network messages that are not necessary but could negatively affect FPS.
        ///Too large a value for METSN may prevent desirable network update messages from being sent in a timely manner, causing units to appear t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ServerController_Arma3_ServerCfg_MinErrorToSendNear_Description {
            get {
                return ResourceManager.GetString("ServerController_Arma3_ServerCfg_MinErrorToSendNear_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal error to send near.
        /// </summary>
        internal static string ServerController_Arma3_ServerCfg_MinErrorToSendNear_Title {
            get {
                return ResourceManager.GetString("ServerController_Arma3_ServerCfg_MinErrorToSendNear_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message displayed when connecting to the server..
        /// </summary>
        internal static string ServerController_Arma3_ServerCfg_Motd_Description {
            get {
                return ResourceManager.GetString("ServerController_Arma3_ServerCfg_Motd_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motd.
        /// </summary>
        internal static string ServerController_Arma3_ServerCfg_Motd_Title {
            get {
                return ResourceManager.GetString("ServerController_Arma3_ServerCfg_Motd_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password for the connection to the server..
        /// </summary>
        internal static string ServerController_Arma3_ServerCfg_Password_Description {
            get {
                return ResourceManager.GetString("ServerController_Arma3_ServerCfg_Password_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server password.
        /// </summary>
        internal static string ServerController_Arma3_ServerCfg_Password_Title {
            get {
                return ResourceManager.GetString("ServerController_Arma3_ServerCfg_Password_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password to protect admin access via &quot;#login &lt;PASSWORD&gt;&quot;..
        /// </summary>
        internal static string ServerController_Arma3_ServerCfg_PasswordAdmin_Description {
            get {
                return ResourceManager.GetString("ServerController_Arma3_ServerCfg_PasswordAdmin_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin password.
        /// </summary>
        internal static string ServerController_Arma3_ServerCfg_PasswordAdmin_Title {
            get {
                return ResourceManager.GetString("ServerController_Arma3_ServerCfg_PasswordAdmin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password required for the alternative syntax of serverCommand&apos;s server-side scripting (case-sensitive)..
        /// </summary>
        internal static string ServerController_Arma3_ServerCfg_ServerCommandPassword_Description {
            get {
                return ResourceManager.GetString("ServerController_Arma3_ServerCfg_ServerCommandPassword_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQF command password.
        /// </summary>
        internal static string ServerController_Arma3_ServerCfg_ServerCommandPassword_Title {
            get {
                return ResourceManager.GetString("ServerController_Arma3_ServerCfg_ServerCommandPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum size of the packet sent over the network. This can be set independently for both client-to-server and server-to-client(s)!
        ///!!! Only use if your router or ISP enforces a smaller packet size and you have connection problems with the game.
        ///Desync could happen if MaxSizeGuaranteed/MaxSizeNonuaranteed values above maxPacketSize are used..
        /// </summary>
        internal static string ServerController_Arma3_ServerCfg_SocketsMaxPacketSize_Description {
            get {
                return ResourceManager.GetString("ServerController_Arma3_ServerCfg_SocketsMaxPacketSize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max package size.
        /// </summary>
        internal static string ServerController_Arma3_ServerCfg_SocketsMaxPacketSize_Title {
            get {
                return ResourceManager.GetString("ServerController_Arma3_ServerCfg_SocketsMaxPacketSize_Title", resourceCulture);
            }
        }
    }
}
