// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Folders.Item.Files;
using X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Folders.Item.Item;
using X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Folders.Item.Upload;
namespace X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Folders.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \game-servers\{gameServerId}\folders\{folder}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithFolderItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The files property</summary>
        public global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Folders.Item.Files.FilesRequestBuilder Files
        {
            get => new global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Folders.Item.Files.FilesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The upload property</summary>
        public global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Folders.Item.Upload.UploadRequestBuilder Upload
        {
            get => new global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Folders.Item.Upload.UploadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the X39.UnitedTacticalForces.WebApp.Api.gameServers.item.folders.item.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Folders.Item.Item.WithFileItemRequestBuilder"/></returns>
        public global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Folders.Item.Item.WithFileItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("file", position);
                return new global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Folders.Item.Item.WithFileItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Folders.Item.WithFolderItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithFolderItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/game-servers/{gameServerId}/folders/{folder}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Folders.Item.WithFolderItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithFolderItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/game-servers/{gameServerId}/folders/{folder}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
