// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using X39.UnitedTacticalForces.WebApp.Api.ResourceClaim.Claims.Item;
namespace X39.UnitedTacticalForces.WebApp.Api.ResourceClaim.Claims
{
    /// <summary>
    /// Builds and executes requests for operations under \resource-claim\claims
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ClaimsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the X39.UnitedTacticalForces.WebApp.Api.resourceClaim.claims.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::X39.UnitedTacticalForces.WebApp.Api.ResourceClaim.Claims.Item.WithClaimItemRequestBuilder"/></returns>
        public global::X39.UnitedTacticalForces.WebApp.Api.ResourceClaim.Claims.Item.WithClaimItemRequestBuilder this[long position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("claimId", position);
                return new global::X39.UnitedTacticalForces.WebApp.Api.ResourceClaim.Claims.Item.WithClaimItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the X39.UnitedTacticalForces.WebApp.Api.resourceClaim.claims.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::X39.UnitedTacticalForces.WebApp.Api.ResourceClaim.Claims.Item.WithClaimItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::X39.UnitedTacticalForces.WebApp.Api.ResourceClaim.Claims.Item.WithClaimItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("claimId", position);
                return new global::X39.UnitedTacticalForces.WebApp.Api.ResourceClaim.Claims.Item.WithClaimItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.ResourceClaim.Claims.ClaimsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ClaimsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/resource-claim/claims", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.ResourceClaim.Claims.ClaimsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ClaimsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/resource-claim/claims", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
