// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using X39.UnitedTacticalForces.WebApp.Api.ModPacks.Item.ChangeOwner;
using X39.UnitedTacticalForces.WebApp.Api.ModPacks.Item.Delete;
using X39.UnitedTacticalForces.WebApp.Api.ModPacks.Item.Download;
using X39.UnitedTacticalForces.WebApp.Api.ModPacks.Item.Update;
using X39.UnitedTacticalForces.WebApp.Api.Models;
namespace X39.UnitedTacticalForces.WebApp.Api.ModPacks.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \mod-packs\{modPackDefinition-id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ModPackDefinitionItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The changeOwner property</summary>
        public global::X39.UnitedTacticalForces.WebApp.Api.ModPacks.Item.ChangeOwner.ChangeOwnerRequestBuilder ChangeOwner
        {
            get => new global::X39.UnitedTacticalForces.WebApp.Api.ModPacks.Item.ChangeOwner.ChangeOwnerRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The deletePath property</summary>
        public global::X39.UnitedTacticalForces.WebApp.Api.ModPacks.Item.Delete.DeleteRequestBuilder DeletePath
        {
            get => new global::X39.UnitedTacticalForces.WebApp.Api.ModPacks.Item.Delete.DeleteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The download property</summary>
        public global::X39.UnitedTacticalForces.WebApp.Api.ModPacks.Item.Download.DownloadRequestBuilder Download
        {
            get => new global::X39.UnitedTacticalForces.WebApp.Api.ModPacks.Item.Download.DownloadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The update property</summary>
        public global::X39.UnitedTacticalForces.WebApp.Api.ModPacks.Item.Update.UpdateRequestBuilder Update
        {
            get => new global::X39.UnitedTacticalForces.WebApp.Api.ModPacks.Item.Update.UpdateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.ModPacks.Item.ModPackDefinitionItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ModPackDefinitionItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/mod-packs/{modPackDefinition%2Did}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.ModPacks.Item.ModPackDefinitionItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ModPackDefinitionItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/mod-packs/{modPackDefinition%2Did}", rawUrl)
        {
        }
        /// <returns>A <see cref="global::X39.UnitedTacticalForces.WebApp.Api.Models.PlainModPackDefinitionDto"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::X39.UnitedTacticalForces.WebApp.Api.Models.PlainModPackDefinitionDto?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::X39.UnitedTacticalForces.WebApp.Api.Models.PlainModPackDefinitionDto> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::X39.UnitedTacticalForces.WebApp.Api.Models.PlainModPackDefinitionDto>(requestInfo, global::X39.UnitedTacticalForces.WebApp.Api.Models.PlainModPackDefinitionDto.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json, text/plain;q=0.9");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::X39.UnitedTacticalForces.WebApp.Api.ModPacks.Item.ModPackDefinitionItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::X39.UnitedTacticalForces.WebApp.Api.ModPacks.Item.ModPackDefinitionItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::X39.UnitedTacticalForces.WebApp.Api.ModPacks.Item.ModPackDefinitionItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ModPackDefinitionItemRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
