// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Configuration;
using X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Delete;
using X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Folders;
using X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Logs;
using X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.ModPack;
using X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Rename;
using X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Start;
using X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Stop;
using X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Upgrade;
using X39.UnitedTacticalForces.WebApp.Api.Models;
namespace X39.UnitedTacticalForces.WebApp.Api.GameServers.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \game-servers\{gameServerId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithGameServerItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The configuration property</summary>
        public global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Configuration.ConfigurationRequestBuilder Configuration
        {
            get => new global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Configuration.ConfigurationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The deletePath property</summary>
        public global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Delete.DeleteRequestBuilder DeletePath
        {
            get => new global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Delete.DeleteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The folders property</summary>
        public global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Folders.FoldersRequestBuilder Folders
        {
            get => new global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Folders.FoldersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The logs property</summary>
        public global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Logs.LogsRequestBuilder Logs
        {
            get => new global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Logs.LogsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The modPack property</summary>
        public global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.ModPack.ModPackRequestBuilder ModPack
        {
            get => new global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.ModPack.ModPackRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The rename property</summary>
        public global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Rename.RenameRequestBuilder Rename
        {
            get => new global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Rename.RenameRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The start property</summary>
        public global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Start.StartRequestBuilder Start
        {
            get => new global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Start.StartRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The stop property</summary>
        public global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Stop.StopRequestBuilder Stop
        {
            get => new global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Stop.StopRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The upgrade property</summary>
        public global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Upgrade.UpgradeRequestBuilder Upgrade
        {
            get => new global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Upgrade.UpgradeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.WithGameServerItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithGameServerItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/game-servers/{gameServerId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.WithGameServerItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithGameServerItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/game-servers/{gameServerId}", rawUrl)
        {
        }
        /// <returns>A <see cref="global::X39.UnitedTacticalForces.WebApp.Api.Models.GameServerInfoDto"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::X39.UnitedTacticalForces.WebApp.Api.Models.GameServerInfoDto?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::X39.UnitedTacticalForces.WebApp.Api.Models.GameServerInfoDto> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::X39.UnitedTacticalForces.WebApp.Api.Models.GameServerInfoDto>(requestInfo, global::X39.UnitedTacticalForces.WebApp.Api.Models.GameServerInfoDto.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json, text/plain;q=0.9");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.WithGameServerItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.WithGameServerItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.WithGameServerItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithGameServerItemRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
