// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using X39.UnitedTacticalForces.WebApp.Api.Roles.Available;
using X39.UnitedTacticalForces.WebApp.Api.Roles.ClaimsOf;
using X39.UnitedTacticalForces.WebApp.Api.Roles.Create;
using X39.UnitedTacticalForces.WebApp.Api.Roles.Delete;
using X39.UnitedTacticalForces.WebApp.Api.Roles.Set;
namespace X39.UnitedTacticalForces.WebApp.Api.Roles
{
    /// <summary>
    /// Builds and executes requests for operations under \roles
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RolesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The available property</summary>
        public global::X39.UnitedTacticalForces.WebApp.Api.Roles.Available.AvailableRequestBuilder Available
        {
            get => new global::X39.UnitedTacticalForces.WebApp.Api.Roles.Available.AvailableRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The claimsOf property</summary>
        public global::X39.UnitedTacticalForces.WebApp.Api.Roles.ClaimsOf.ClaimsOfRequestBuilder ClaimsOf
        {
            get => new global::X39.UnitedTacticalForces.WebApp.Api.Roles.ClaimsOf.ClaimsOfRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The create property</summary>
        public global::X39.UnitedTacticalForces.WebApp.Api.Roles.Create.CreateRequestBuilder Create
        {
            get => new global::X39.UnitedTacticalForces.WebApp.Api.Roles.Create.CreateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The deletePath property</summary>
        public global::X39.UnitedTacticalForces.WebApp.Api.Roles.Delete.DeleteRequestBuilder DeletePath
        {
            get => new global::X39.UnitedTacticalForces.WebApp.Api.Roles.Delete.DeleteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The set property</summary>
        public global::X39.UnitedTacticalForces.WebApp.Api.Roles.Set.SetRequestBuilder Set
        {
            get => new global::X39.UnitedTacticalForces.WebApp.Api.Roles.Set.SetRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.Roles.RolesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RolesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/roles", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.Roles.RolesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RolesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/roles", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
