// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using X39.UnitedTacticalForces.WebApp.Api.ModPacks.Item.Update.Composition;
using X39.UnitedTacticalForces.WebApp.Api.ModPacks.Item.Update.Standalone;
namespace X39.UnitedTacticalForces.WebApp.Api.ModPacks.Item.Update
{
    /// <summary>
    /// Builds and executes requests for operations under \mod-packs\{modPackDefinition-id}\update
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UpdateRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The composition property</summary>
        public global::X39.UnitedTacticalForces.WebApp.Api.ModPacks.Item.Update.Composition.CompositionRequestBuilder Composition
        {
            get => new global::X39.UnitedTacticalForces.WebApp.Api.ModPacks.Item.Update.Composition.CompositionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The standalone property</summary>
        public global::X39.UnitedTacticalForces.WebApp.Api.ModPacks.Item.Update.Standalone.StandaloneRequestBuilder Standalone
        {
            get => new global::X39.UnitedTacticalForces.WebApp.Api.ModPacks.Item.Update.Standalone.StandaloneRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.ModPacks.Item.Update.UpdateRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UpdateRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/mod-packs/{modPackDefinition%2Did}/update", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.ModPacks.Item.Update.UpdateRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UpdateRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/mod-packs/{modPackDefinition%2Did}/update", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
