// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using X39.UnitedTacticalForces.WebApp.Api.ResourceClaim.Item.Item.Users.Item.Add;
using X39.UnitedTacticalForces.WebApp.Api.ResourceClaim.Item.Item.Users.Item.Remove;
namespace X39.UnitedTacticalForces.WebApp.Api.ResourceClaim.Item.Item.Users.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \resource-claim\{resourcePrefix}\{resourceIdentifier}\users\{userId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithUserItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The add property</summary>
        public global::X39.UnitedTacticalForces.WebApp.Api.ResourceClaim.Item.Item.Users.Item.Add.AddRequestBuilder Add
        {
            get => new global::X39.UnitedTacticalForces.WebApp.Api.ResourceClaim.Item.Item.Users.Item.Add.AddRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The remove property</summary>
        public global::X39.UnitedTacticalForces.WebApp.Api.ResourceClaim.Item.Item.Users.Item.Remove.RemoveRequestBuilder Remove
        {
            get => new global::X39.UnitedTacticalForces.WebApp.Api.ResourceClaim.Item.Item.Users.Item.Remove.RemoveRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.ResourceClaim.Item.Item.Users.Item.WithUserItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithUserItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/resource-claim/{resourcePrefix}/{resourceIdentifier}/users/{userId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.ResourceClaim.Item.Item.Users.Item.WithUserItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithUserItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/resource-claim/{resourcePrefix}/{resourceIdentifier}/users/{userId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
