// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using X39.UnitedTacticalForces.WebApp.Api.Roles.Set.User.Item.Role.Item.To.Item;
namespace X39.UnitedTacticalForces.WebApp.Api.Roles.Set.User.Item.Role.Item.To
{
    /// <summary>
    /// Builds and executes requests for operations under \roles\set\user\{userId}\role\{roleId}\to
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ToRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the X39.UnitedTacticalForces.WebApp.Api.roles.set.user.item.role.item.to.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::X39.UnitedTacticalForces.WebApp.Api.Roles.Set.User.Item.Role.Item.To.Item.WithModeItemRequestBuilder"/></returns>
        public global::X39.UnitedTacticalForces.WebApp.Api.Roles.Set.User.Item.Role.Item.To.Item.WithModeItemRequestBuilder this[bool position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("mode", position);
                return new global::X39.UnitedTacticalForces.WebApp.Api.Roles.Set.User.Item.Role.Item.To.Item.WithModeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the X39.UnitedTacticalForces.WebApp.Api.roles.set.user.item.role.item.to.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::X39.UnitedTacticalForces.WebApp.Api.Roles.Set.User.Item.Role.Item.To.Item.WithModeItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::X39.UnitedTacticalForces.WebApp.Api.Roles.Set.User.Item.Role.Item.To.Item.WithModeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("mode", position);
                return new global::X39.UnitedTacticalForces.WebApp.Api.Roles.Set.User.Item.Role.Item.To.Item.WithModeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.Roles.Set.User.Item.Role.Item.To.ToRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ToRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/roles/set/user/{userId}/role/{roleId}/to", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.Roles.Set.User.Item.Role.Item.To.ToRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ToRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/roles/set/user/{userId}/role/{roleId}/to", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
