// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Folders.Item.Item.Delete;
using X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Folders.Item.Item.Get;
namespace X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Folders.Item.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \game-servers\{gameServerId}\folders\{folder}\{file}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithFileItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The deletePath property</summary>
        public global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Folders.Item.Item.Delete.DeleteRequestBuilder DeletePath
        {
            get => new global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Folders.Item.Item.Delete.DeleteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The getPath property</summary>
        public global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Folders.Item.Item.Get.GetRequestBuilder GetPath
        {
            get => new global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Folders.Item.Item.Get.GetRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Folders.Item.Item.WithFileItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithFileItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/game-servers/{gameServerId}/folders/{folder}/{file}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Folders.Item.Item.WithFileItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithFileItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/game-servers/{gameServerId}/folders/{folder}/{file}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
