// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using X39.UnitedTacticalForces.WebApp.Api.ResourceClaim.Item.Item.Roles;
using X39.UnitedTacticalForces.WebApp.Api.ResourceClaim.Item.Item.Users;
using X39.UnitedTacticalForces.WebApp.Api.ResourceClaim.Item.Item.UsersAndRoles;
namespace X39.UnitedTacticalForces.WebApp.Api.ResourceClaim.Item.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \resource-claim\{resourcePrefix}\{resourceIdentifier}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithResourceIdentifierItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The roles property</summary>
        public global::X39.UnitedTacticalForces.WebApp.Api.ResourceClaim.Item.Item.Roles.RolesRequestBuilder Roles
        {
            get => new global::X39.UnitedTacticalForces.WebApp.Api.ResourceClaim.Item.Item.Roles.RolesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::X39.UnitedTacticalForces.WebApp.Api.ResourceClaim.Item.Item.Users.UsersRequestBuilder Users
        {
            get => new global::X39.UnitedTacticalForces.WebApp.Api.ResourceClaim.Item.Item.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The usersAndRoles property</summary>
        public global::X39.UnitedTacticalForces.WebApp.Api.ResourceClaim.Item.Item.UsersAndRoles.UsersAndRolesRequestBuilder UsersAndRoles
        {
            get => new global::X39.UnitedTacticalForces.WebApp.Api.ResourceClaim.Item.Item.UsersAndRoles.UsersAndRolesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.ResourceClaim.Item.Item.WithResourceIdentifierItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithResourceIdentifierItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/resource-claim/{resourcePrefix}/{resourceIdentifier}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.ResourceClaim.Item.Item.WithResourceIdentifierItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithResourceIdentifierItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/resource-claim/{resourcePrefix}/{resourceIdentifier}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
