// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace X39.UnitedTacticalForces.WebApp.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ConfigurationEntryDefinition : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The allowedValues property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::X39.UnitedTacticalForces.WebApp.Api.Models.ValuePair>? AllowedValues { get; set; }
#nullable restore
#else
        public List<global::X39.UnitedTacticalForces.WebApp.Api.Models.ValuePair> AllowedValues { get; set; }
#endif
        /// <summary>The defaultValue property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultValue { get; set; }
#nullable restore
#else
        public string DefaultValue { get; set; }
#endif
        /// <summary>The displayDescription property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayDescription { get; set; }
#nullable restore
#else
        public string DisplayDescription { get; set; }
#endif
        /// <summary>The displayGroup property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayGroup { get; set; }
#nullable restore
#else
        public string DisplayGroup { get; set; }
#endif
        /// <summary>The displayName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>The identifier property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Identifier { get; set; }
#nullable restore
#else
        public string Identifier { get; set; }
#endif
        /// <summary>The kind property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::X39.UnitedTacticalForces.WebApp.Api.Models.EConfigurationEntryKind? Kind { get; set; }
#nullable restore
#else
        public global::X39.UnitedTacticalForces.WebApp.Api.Models.EConfigurationEntryKind Kind { get; set; }
#endif
        /// <summary>The maxValue property</summary>
        public double? MaxValue { get; set; }
        /// <summary>The minValue property</summary>
        public double? MinValue { get; set; }
        /// <summary>The path property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Path { get; set; }
#nullable restore
#else
        public string Path { get; set; }
#endif
        /// <summary>The realm property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Realm { get; set; }
#nullable restore
#else
        public string Realm { get; set; }
#endif
        /// <summary>The regex property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Regex { get; set; }
#nullable restore
#else
        public string Regex { get; set; }
#endif
        /// <summary>The required property</summary>
        public bool? Required { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.Models.ConfigurationEntryDefinition"/> and sets the default values.
        /// </summary>
        public ConfigurationEntryDefinition()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::X39.UnitedTacticalForces.WebApp.Api.Models.ConfigurationEntryDefinition"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::X39.UnitedTacticalForces.WebApp.Api.Models.ConfigurationEntryDefinition CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::X39.UnitedTacticalForces.WebApp.Api.Models.ConfigurationEntryDefinition();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allowedValues", n => { AllowedValues = n.GetCollectionOfObjectValues<global::X39.UnitedTacticalForces.WebApp.Api.Models.ValuePair>(global::X39.UnitedTacticalForces.WebApp.Api.Models.ValuePair.CreateFromDiscriminatorValue)?.AsList(); } },
                { "defaultValue", n => { DefaultValue = n.GetStringValue(); } },
                { "displayDescription", n => { DisplayDescription = n.GetStringValue(); } },
                { "displayGroup", n => { DisplayGroup = n.GetStringValue(); } },
                { "displayName", n => { DisplayName = n.GetStringValue(); } },
                { "identifier", n => { Identifier = n.GetStringValue(); } },
                { "kind", n => { Kind = n.GetObjectValue<global::X39.UnitedTacticalForces.WebApp.Api.Models.EConfigurationEntryKind>(global::X39.UnitedTacticalForces.WebApp.Api.Models.EConfigurationEntryKind.CreateFromDiscriminatorValue); } },
                { "maxValue", n => { MaxValue = n.GetDoubleValue(); } },
                { "minValue", n => { MinValue = n.GetDoubleValue(); } },
                { "path", n => { Path = n.GetStringValue(); } },
                { "realm", n => { Realm = n.GetStringValue(); } },
                { "regex", n => { Regex = n.GetStringValue(); } },
                { "required", n => { Required = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::X39.UnitedTacticalForces.WebApp.Api.Models.ValuePair>("allowedValues", AllowedValues);
            writer.WriteStringValue("defaultValue", DefaultValue);
            writer.WriteStringValue("displayDescription", DisplayDescription);
            writer.WriteStringValue("displayGroup", DisplayGroup);
            writer.WriteStringValue("displayName", DisplayName);
            writer.WriteStringValue("identifier", Identifier);
            writer.WriteObjectValue<global::X39.UnitedTacticalForces.WebApp.Api.Models.EConfigurationEntryKind>("kind", Kind);
            writer.WriteDoubleValue("maxValue", MaxValue);
            writer.WriteDoubleValue("minValue", MinValue);
            writer.WriteStringValue("path", Path);
            writer.WriteStringValue("realm", Realm);
            writer.WriteStringValue("regex", Regex);
            writer.WriteBoolValue("required", Required);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
