// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace X39.UnitedTacticalForces.WebApp.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class FileStreamResult : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The contentType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContentType { get; set; }
#nullable restore
#else
        public string ContentType { get; set; }
#endif
        /// <summary>The enableRangeProcessing property</summary>
        public bool? EnableRangeProcessing { get; set; }
        /// <summary>The entityTag property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::X39.UnitedTacticalForces.WebApp.Api.Models.EntityTagHeaderValue? EntityTag { get; set; }
#nullable restore
#else
        public global::X39.UnitedTacticalForces.WebApp.Api.Models.EntityTagHeaderValue EntityTag { get; set; }
#endif
        /// <summary>The fileDownloadName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FileDownloadName { get; set; }
#nullable restore
#else
        public string FileDownloadName { get; set; }
#endif
        /// <summary>The fileStream property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public byte[]? FileStream { get; set; }
#nullable restore
#else
        public byte[] FileStream { get; set; }
#endif
        /// <summary>The lastModified property</summary>
        public DateTimeOffset? LastModified { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.Models.FileStreamResult"/> and sets the default values.
        /// </summary>
        public FileStreamResult()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::X39.UnitedTacticalForces.WebApp.Api.Models.FileStreamResult"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::X39.UnitedTacticalForces.WebApp.Api.Models.FileStreamResult CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::X39.UnitedTacticalForces.WebApp.Api.Models.FileStreamResult();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "contentType", n => { ContentType = n.GetStringValue(); } },
                { "enableRangeProcessing", n => { EnableRangeProcessing = n.GetBoolValue(); } },
                { "entityTag", n => { EntityTag = n.GetObjectValue<global::X39.UnitedTacticalForces.WebApp.Api.Models.EntityTagHeaderValue>(global::X39.UnitedTacticalForces.WebApp.Api.Models.EntityTagHeaderValue.CreateFromDiscriminatorValue); } },
                { "fileDownloadName", n => { FileDownloadName = n.GetStringValue(); } },
                { "fileStream", n => { FileStream = n.GetByteArrayValue(); } },
                { "lastModified", n => { LastModified = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("contentType", ContentType);
            writer.WriteBoolValue("enableRangeProcessing", EnableRangeProcessing);
            writer.WriteObjectValue<global::X39.UnitedTacticalForces.WebApp.Api.Models.EntityTagHeaderValue>("entityTag", EntityTag);
            writer.WriteStringValue("fileDownloadName", FileDownloadName);
            writer.WriteByteArrayValue("fileStream", FileStream);
            writer.WriteDateTimeOffsetValue("lastModified", LastModified);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
