// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace X39.UnitedTacticalForces.WebApp.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class FullModPackDefinitionDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The isActive property</summary>
        public bool? IsActive { get; set; }
        /// <summary>The isComposition property</summary>
        public bool? IsComposition { get; set; }
        /// <summary>The modPackRevisions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::X39.UnitedTacticalForces.WebApp.Api.Models.PlainModPackRevisionDto>? ModPackRevisions { get; set; }
#nullable restore
#else
        public List<global::X39.UnitedTacticalForces.WebApp.Api.Models.PlainModPackRevisionDto> ModPackRevisions { get; set; }
#endif
        /// <summary>The owner property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::X39.UnitedTacticalForces.WebApp.Api.Models.PlainUserDto2? Owner { get; set; }
#nullable restore
#else
        public global::X39.UnitedTacticalForces.WebApp.Api.Models.PlainUserDto2 Owner { get; set; }
#endif
        /// <summary>The primaryKey property</summary>
        public long? PrimaryKey { get; set; }
        /// <summary>The timeStampCreated property</summary>
        public DateTimeOffset? TimeStampCreated { get; set; }
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.Models.FullModPackDefinitionDto"/> and sets the default values.
        /// </summary>
        public FullModPackDefinitionDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::X39.UnitedTacticalForces.WebApp.Api.Models.FullModPackDefinitionDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::X39.UnitedTacticalForces.WebApp.Api.Models.FullModPackDefinitionDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::X39.UnitedTacticalForces.WebApp.Api.Models.FullModPackDefinitionDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "isActive", n => { IsActive = n.GetBoolValue(); } },
                { "isComposition", n => { IsComposition = n.GetBoolValue(); } },
                { "modPackRevisions", n => { ModPackRevisions = n.GetCollectionOfObjectValues<global::X39.UnitedTacticalForces.WebApp.Api.Models.PlainModPackRevisionDto>(global::X39.UnitedTacticalForces.WebApp.Api.Models.PlainModPackRevisionDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "owner", n => { Owner = n.GetObjectValue<global::X39.UnitedTacticalForces.WebApp.Api.Models.PlainUserDto2>(global::X39.UnitedTacticalForces.WebApp.Api.Models.PlainUserDto2.CreateFromDiscriminatorValue); } },
                { "primaryKey", n => { PrimaryKey = n.GetLongValue(); } },
                { "timeStampCreated", n => { TimeStampCreated = n.GetDateTimeOffsetValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("isActive", IsActive);
            writer.WriteBoolValue("isComposition", IsComposition);
            writer.WriteCollectionOfObjectValues<global::X39.UnitedTacticalForces.WebApp.Api.Models.PlainModPackRevisionDto>("modPackRevisions", ModPackRevisions);
            writer.WriteObjectValue<global::X39.UnitedTacticalForces.WebApp.Api.Models.PlainUserDto2>("owner", Owner);
            writer.WriteLongValue("primaryKey", PrimaryKey);
            writer.WriteDateTimeOffsetValue("timeStampCreated", TimeStampCreated);
            writer.WriteStringValue("title", Title);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
