// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace X39.UnitedTacticalForces.WebApp.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GameServerInfoDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The canStart property</summary>
        public bool? CanStart { get; set; }
        /// <summary>The canStop property</summary>
        public bool? CanStop { get; set; }
        /// <summary>The canUpdateConfiguration property</summary>
        public bool? CanUpdateConfiguration { get; set; }
        /// <summary>The canUpgrade property</summary>
        public bool? CanUpgrade { get; set; }
        /// <summary>The gameServer property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::X39.UnitedTacticalForces.WebApp.Api.Models.PlainGameServerDto? GameServer { get; set; }
#nullable restore
#else
        public global::X39.UnitedTacticalForces.WebApp.Api.Models.PlainGameServerDto GameServer { get; set; }
#endif
        /// <summary>The isRunning property</summary>
        public bool? IsRunning { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.Models.GameServerInfoDto"/> and sets the default values.
        /// </summary>
        public GameServerInfoDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::X39.UnitedTacticalForces.WebApp.Api.Models.GameServerInfoDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::X39.UnitedTacticalForces.WebApp.Api.Models.GameServerInfoDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::X39.UnitedTacticalForces.WebApp.Api.Models.GameServerInfoDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "canStart", n => { CanStart = n.GetBoolValue(); } },
                { "canStop", n => { CanStop = n.GetBoolValue(); } },
                { "canUpdateConfiguration", n => { CanUpdateConfiguration = n.GetBoolValue(); } },
                { "canUpgrade", n => { CanUpgrade = n.GetBoolValue(); } },
                { "gameServer", n => { GameServer = n.GetObjectValue<global::X39.UnitedTacticalForces.WebApp.Api.Models.PlainGameServerDto>(global::X39.UnitedTacticalForces.WebApp.Api.Models.PlainGameServerDto.CreateFromDiscriminatorValue); } },
                { "isRunning", n => { IsRunning = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("canStart", CanStart);
            writer.WriteBoolValue("canStop", CanStop);
            writer.WriteBoolValue("canUpdateConfiguration", CanUpdateConfiguration);
            writer.WriteBoolValue("canUpgrade", CanUpgrade);
            writer.WriteObjectValue<global::X39.UnitedTacticalForces.WebApp.Api.Models.PlainGameServerDto>("gameServer", GameServer);
            writer.WriteBoolValue("isRunning", IsRunning);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
