// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Serialization;
namespace X39.UnitedTacticalForces.WebApp.Api.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="int"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LogLevel : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="int"/></summary>
        public int? Integer { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::X39.UnitedTacticalForces.WebApp.Api.Models.LogLevel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::X39.UnitedTacticalForces.WebApp.Api.Models.LogLevel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::X39.UnitedTacticalForces.WebApp.Api.Models.LogLevel();
            if(parseNode.GetIntValue() is int integerValue)
            {
                result.Integer = integerValue;
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            if(Integer != null)
            {
                writer.WriteIntValue(null, Integer);
            }
        }
    }
}
#pragma warning restore CS0618
