// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace X39.UnitedTacticalForces.WebApp.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ModPackRevisionDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The definitionIsActive property</summary>
        public bool? DefinitionIsActive { get; set; }
        /// <summary>The definitionIsComposition property</summary>
        public bool? DefinitionIsComposition { get; set; }
        /// <summary>The definitionOwnerFk property</summary>
        public Guid? DefinitionOwnerFk { get; set; }
        /// <summary>The definitionPrimaryKey property</summary>
        public long? DefinitionPrimaryKey { get; set; }
        /// <summary>The definitionTimeStampCreated property</summary>
        public DateTimeOffset? DefinitionTimeStampCreated { get; set; }
        /// <summary>The definitionTitle property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefinitionTitle { get; set; }
#nullable restore
#else
        public string DefinitionTitle { get; set; }
#endif
        /// <summary>The html property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Html { get; set; }
#nullable restore
#else
        public string Html { get; set; }
#endif
        /// <summary>The isActive property</summary>
        public bool? IsActive { get; set; }
        /// <summary>The metaTimeStampDownloaded property</summary>
        public DateTimeOffset? MetaTimeStampDownloaded { get; set; }
        /// <summary>The primaryKey property</summary>
        public long? PrimaryKey { get; set; }
        /// <summary>The timeStampCreated property</summary>
        public DateTimeOffset? TimeStampCreated { get; set; }
        /// <summary>The updatedByFk property</summary>
        public Guid? UpdatedByFk { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.Models.ModPackRevisionDto"/> and sets the default values.
        /// </summary>
        public ModPackRevisionDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::X39.UnitedTacticalForces.WebApp.Api.Models.ModPackRevisionDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::X39.UnitedTacticalForces.WebApp.Api.Models.ModPackRevisionDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::X39.UnitedTacticalForces.WebApp.Api.Models.ModPackRevisionDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "definitionIsActive", n => { DefinitionIsActive = n.GetBoolValue(); } },
                { "definitionIsComposition", n => { DefinitionIsComposition = n.GetBoolValue(); } },
                { "definitionOwnerFk", n => { DefinitionOwnerFk = n.GetGuidValue(); } },
                { "definitionPrimaryKey", n => { DefinitionPrimaryKey = n.GetLongValue(); } },
                { "definitionTimeStampCreated", n => { DefinitionTimeStampCreated = n.GetDateTimeOffsetValue(); } },
                { "definitionTitle", n => { DefinitionTitle = n.GetStringValue(); } },
                { "html", n => { Html = n.GetStringValue(); } },
                { "isActive", n => { IsActive = n.GetBoolValue(); } },
                { "metaTimeStampDownloaded", n => { MetaTimeStampDownloaded = n.GetDateTimeOffsetValue(); } },
                { "primaryKey", n => { PrimaryKey = n.GetLongValue(); } },
                { "timeStampCreated", n => { TimeStampCreated = n.GetDateTimeOffsetValue(); } },
                { "updatedByFk", n => { UpdatedByFk = n.GetGuidValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("definitionIsActive", DefinitionIsActive);
            writer.WriteBoolValue("definitionIsComposition", DefinitionIsComposition);
            writer.WriteGuidValue("definitionOwnerFk", DefinitionOwnerFk);
            writer.WriteLongValue("definitionPrimaryKey", DefinitionPrimaryKey);
            writer.WriteDateTimeOffsetValue("definitionTimeStampCreated", DefinitionTimeStampCreated);
            writer.WriteStringValue("definitionTitle", DefinitionTitle);
            writer.WriteStringValue("html", Html);
            writer.WriteBoolValue("isActive", IsActive);
            writer.WriteDateTimeOffsetValue("metaTimeStampDownloaded", MetaTimeStampDownloaded);
            writer.WriteLongValue("primaryKey", PrimaryKey);
            writer.WriteDateTimeOffsetValue("timeStampCreated", TimeStampCreated);
            writer.WriteGuidValue("updatedByFk", UpdatedByFk);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
