// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace X39.UnitedTacticalForces.WebApp.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ModPackDefinitionDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The isActive property</summary>
        public bool? IsActive { get; set; }
        /// <summary>The isComposition property</summary>
        public bool? IsComposition { get; set; }
        /// <summary>The metaTimeStampDownloaded property</summary>
        public DateTimeOffset? MetaTimeStampDownloaded { get; set; }
        /// <summary>The ownerFk property</summary>
        public Guid? OwnerFk { get; set; }
        /// <summary>The primaryKey property</summary>
        public long? PrimaryKey { get; set; }
        /// <summary>The revisionHtml property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RevisionHtml { get; set; }
#nullable restore
#else
        public string RevisionHtml { get; set; }
#endif
        /// <summary>The revisionIsActive property</summary>
        public bool? RevisionIsActive { get; set; }
        /// <summary>The revisionPrimaryKey property</summary>
        public long? RevisionPrimaryKey { get; set; }
        /// <summary>The revisionTimeStampCreated property</summary>
        public DateTimeOffset? RevisionTimeStampCreated { get; set; }
        /// <summary>The revisionUpdatedByFk property</summary>
        public Guid? RevisionUpdatedByFk { get; set; }
        /// <summary>The timeStampCreated property</summary>
        public DateTimeOffset? TimeStampCreated { get; set; }
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.Models.ModPackDefinitionDto"/> and sets the default values.
        /// </summary>
        public ModPackDefinitionDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::X39.UnitedTacticalForces.WebApp.Api.Models.ModPackDefinitionDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::X39.UnitedTacticalForces.WebApp.Api.Models.ModPackDefinitionDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::X39.UnitedTacticalForces.WebApp.Api.Models.ModPackDefinitionDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "isActive", n => { IsActive = n.GetBoolValue(); } },
                { "isComposition", n => { IsComposition = n.GetBoolValue(); } },
                { "metaTimeStampDownloaded", n => { MetaTimeStampDownloaded = n.GetDateTimeOffsetValue(); } },
                { "ownerFk", n => { OwnerFk = n.GetGuidValue(); } },
                { "primaryKey", n => { PrimaryKey = n.GetLongValue(); } },
                { "revisionHtml", n => { RevisionHtml = n.GetStringValue(); } },
                { "revisionIsActive", n => { RevisionIsActive = n.GetBoolValue(); } },
                { "revisionPrimaryKey", n => { RevisionPrimaryKey = n.GetLongValue(); } },
                { "revisionTimeStampCreated", n => { RevisionTimeStampCreated = n.GetDateTimeOffsetValue(); } },
                { "revisionUpdatedByFk", n => { RevisionUpdatedByFk = n.GetGuidValue(); } },
                { "timeStampCreated", n => { TimeStampCreated = n.GetDateTimeOffsetValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("isActive", IsActive);
            writer.WriteBoolValue("isComposition", IsComposition);
            writer.WriteDateTimeOffsetValue("metaTimeStampDownloaded", MetaTimeStampDownloaded);
            writer.WriteGuidValue("ownerFk", OwnerFk);
            writer.WriteLongValue("primaryKey", PrimaryKey);
            writer.WriteStringValue("revisionHtml", RevisionHtml);
            writer.WriteBoolValue("revisionIsActive", RevisionIsActive);
            writer.WriteLongValue("revisionPrimaryKey", RevisionPrimaryKey);
            writer.WriteDateTimeOffsetValue("revisionTimeStampCreated", RevisionTimeStampCreated);
            writer.WriteGuidValue("revisionUpdatedByFk", RevisionUpdatedByFk);
            writer.WriteDateTimeOffsetValue("timeStampCreated", TimeStampCreated);
            writer.WriteStringValue("title", Title);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
