// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace X39.UnitedTacticalForces.WebApp.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PlainEventDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The acceptedCount property</summary>
        public int? AcceptedCount { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The hostedByFk property</summary>
        public Guid? HostedByFk { get; set; }
        /// <summary>The image property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public byte[]? Image { get; set; }
#nullable restore
#else
        public byte[] Image { get; set; }
#endif
        /// <summary>The imageMimeType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ImageMimeType { get; set; }
#nullable restore
#else
        public string ImageMimeType { get; set; }
#endif
        /// <summary>The isVisible property</summary>
        public bool? IsVisible { get; set; }
        /// <summary>The maybeCount property</summary>
        public int? MaybeCount { get; set; }
        /// <summary>The metaAcceptance property</summary>
        public int? MetaAcceptance { get; set; }
        /// <summary>The minimumAccepted property</summary>
        public int? MinimumAccepted { get; set; }
        /// <summary>The modPackRevisionFk property</summary>
        public long? ModPackRevisionFk { get; set; }
        /// <summary>The ownerFk property</summary>
        public Guid? OwnerFk { get; set; }
        /// <summary>The primaryKey property</summary>
        public Guid? PrimaryKey { get; set; }
        /// <summary>The rejectedCount property</summary>
        public int? RejectedCount { get; set; }
        /// <summary>The scheduledFor property</summary>
        public DateTimeOffset? ScheduledFor { get; set; }
        /// <summary>The scheduledForOriginal property</summary>
        public DateTimeOffset? ScheduledForOriginal { get; set; }
        /// <summary>The terrainFk property</summary>
        public long? TerrainFk { get; set; }
        /// <summary>The timeStampCreated property</summary>
        public DateTimeOffset? TimeStampCreated { get; set; }
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.Models.PlainEventDto"/> and sets the default values.
        /// </summary>
        public PlainEventDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::X39.UnitedTacticalForces.WebApp.Api.Models.PlainEventDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::X39.UnitedTacticalForces.WebApp.Api.Models.PlainEventDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::X39.UnitedTacticalForces.WebApp.Api.Models.PlainEventDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "acceptedCount", n => { AcceptedCount = n.GetIntValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "hostedByFk", n => { HostedByFk = n.GetGuidValue(); } },
                { "image", n => { Image = n.GetByteArrayValue(); } },
                { "imageMimeType", n => { ImageMimeType = n.GetStringValue(); } },
                { "isVisible", n => { IsVisible = n.GetBoolValue(); } },
                { "maybeCount", n => { MaybeCount = n.GetIntValue(); } },
                { "metaAcceptance", n => { MetaAcceptance = n.GetIntValue(); } },
                { "minimumAccepted", n => { MinimumAccepted = n.GetIntValue(); } },
                { "modPackRevisionFk", n => { ModPackRevisionFk = n.GetLongValue(); } },
                { "ownerFk", n => { OwnerFk = n.GetGuidValue(); } },
                { "primaryKey", n => { PrimaryKey = n.GetGuidValue(); } },
                { "rejectedCount", n => { RejectedCount = n.GetIntValue(); } },
                { "scheduledFor", n => { ScheduledFor = n.GetDateTimeOffsetValue(); } },
                { "scheduledForOriginal", n => { ScheduledForOriginal = n.GetDateTimeOffsetValue(); } },
                { "terrainFk", n => { TerrainFk = n.GetLongValue(); } },
                { "timeStampCreated", n => { TimeStampCreated = n.GetDateTimeOffsetValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("acceptedCount", AcceptedCount);
            writer.WriteStringValue("description", Description);
            writer.WriteGuidValue("hostedByFk", HostedByFk);
            writer.WriteByteArrayValue("image", Image);
            writer.WriteStringValue("imageMimeType", ImageMimeType);
            writer.WriteBoolValue("isVisible", IsVisible);
            writer.WriteIntValue("maybeCount", MaybeCount);
            writer.WriteIntValue("metaAcceptance", MetaAcceptance);
            writer.WriteIntValue("minimumAccepted", MinimumAccepted);
            writer.WriteLongValue("modPackRevisionFk", ModPackRevisionFk);
            writer.WriteGuidValue("ownerFk", OwnerFk);
            writer.WriteGuidValue("primaryKey", PrimaryKey);
            writer.WriteIntValue("rejectedCount", RejectedCount);
            writer.WriteDateTimeOffsetValue("scheduledFor", ScheduledFor);
            writer.WriteDateTimeOffsetValue("scheduledForOriginal", ScheduledForOriginal);
            writer.WriteLongValue("terrainFk", TerrainFk);
            writer.WriteDateTimeOffsetValue("timeStampCreated", TimeStampCreated);
            writer.WriteStringValue("title", Title);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
