// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace X39.UnitedTacticalForces.WebApp.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PlainConfigurationEntryDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The changedByFk property</summary>
        public Guid? ChangedByFk { get; set; }
        /// <summary>The gameServerFk property</summary>
        public long? GameServerFk { get; set; }
        /// <summary>The isActive property</summary>
        public bool? IsActive { get; set; }
        /// <summary>The isSensitive property</summary>
        public bool? IsSensitive { get; set; }
        /// <summary>The path property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Path { get; set; }
#nullable restore
#else
        public string Path { get; set; }
#endif
        /// <summary>The primaryKey property</summary>
        public long? PrimaryKey { get; set; }
        /// <summary>The realm property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Realm { get; set; }
#nullable restore
#else
        public string Realm { get; set; }
#endif
        /// <summary>The timeStamp property</summary>
        public DateTimeOffset? TimeStamp { get; set; }
        /// <summary>The value property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Value { get; set; }
#nullable restore
#else
        public string Value { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.Models.PlainConfigurationEntryDto"/> and sets the default values.
        /// </summary>
        public PlainConfigurationEntryDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::X39.UnitedTacticalForces.WebApp.Api.Models.PlainConfigurationEntryDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::X39.UnitedTacticalForces.WebApp.Api.Models.PlainConfigurationEntryDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::X39.UnitedTacticalForces.WebApp.Api.Models.PlainConfigurationEntryDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "changedByFk", n => { ChangedByFk = n.GetGuidValue(); } },
                { "gameServerFk", n => { GameServerFk = n.GetLongValue(); } },
                { "isActive", n => { IsActive = n.GetBoolValue(); } },
                { "isSensitive", n => { IsSensitive = n.GetBoolValue(); } },
                { "path", n => { Path = n.GetStringValue(); } },
                { "primaryKey", n => { PrimaryKey = n.GetLongValue(); } },
                { "realm", n => { Realm = n.GetStringValue(); } },
                { "timeStamp", n => { TimeStamp = n.GetDateTimeOffsetValue(); } },
                { "value", n => { Value = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteGuidValue("changedByFk", ChangedByFk);
            writer.WriteLongValue("gameServerFk", GameServerFk);
            writer.WriteBoolValue("isActive", IsActive);
            writer.WriteBoolValue("isSensitive", IsSensitive);
            writer.WriteStringValue("path", Path);
            writer.WriteLongValue("primaryKey", PrimaryKey);
            writer.WriteStringValue("realm", Realm);
            writer.WriteDateTimeOffsetValue("timeStamp", TimeStamp);
            writer.WriteStringValue("value", Value);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
