// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace X39.UnitedTacticalForces.WebApp.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PlainEventSlotDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The assignedToFk property</summary>
        public Guid? AssignedToFk { get; set; }
        /// <summary>The eventFk property</summary>
        public Guid? EventFk { get; set; }
        /// <summary>The group property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Group { get; set; }
#nullable restore
#else
        public string Group { get; set; }
#endif
        /// <summary>The isSelfAssignable property</summary>
        public bool? IsSelfAssignable { get; set; }
        /// <summary>The isVisible property</summary>
        public bool? IsVisible { get; set; }
        /// <summary>The side property</summary>
        public int? Side { get; set; }
        /// <summary>The slotNumber property</summary>
        public int? SlotNumber { get; set; }
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.Models.PlainEventSlotDto"/> and sets the default values.
        /// </summary>
        public PlainEventSlotDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::X39.UnitedTacticalForces.WebApp.Api.Models.PlainEventSlotDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::X39.UnitedTacticalForces.WebApp.Api.Models.PlainEventSlotDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::X39.UnitedTacticalForces.WebApp.Api.Models.PlainEventSlotDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "assignedToFk", n => { AssignedToFk = n.GetGuidValue(); } },
                { "eventFk", n => { EventFk = n.GetGuidValue(); } },
                { "group", n => { Group = n.GetStringValue(); } },
                { "isSelfAssignable", n => { IsSelfAssignable = n.GetBoolValue(); } },
                { "isVisible", n => { IsVisible = n.GetBoolValue(); } },
                { "side", n => { Side = n.GetIntValue(); } },
                { "slotNumber", n => { SlotNumber = n.GetIntValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteGuidValue("assignedToFk", AssignedToFk);
            writer.WriteGuidValue("eventFk", EventFk);
            writer.WriteStringValue("group", Group);
            writer.WriteBoolValue("isSelfAssignable", IsSelfAssignable);
            writer.WriteBoolValue("isVisible", IsVisible);
            writer.WriteIntValue("side", Side);
            writer.WriteIntValue("slotNumber", SlotNumber);
            writer.WriteStringValue("title", Title);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
