// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using X39.UnitedTacticalForces.WebApp.Api.ResourceClaim.Item.Item;
namespace X39.UnitedTacticalForces.WebApp.Api.ResourceClaim.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \resource-claim\{resourcePrefix}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithResourcePrefixItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the X39.UnitedTacticalForces.WebApp.Api.resourceClaim.item.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::X39.UnitedTacticalForces.WebApp.Api.ResourceClaim.Item.Item.WithResourceIdentifierItemRequestBuilder"/></returns>
        public global::X39.UnitedTacticalForces.WebApp.Api.ResourceClaim.Item.Item.WithResourceIdentifierItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("resourceIdentifier", position);
                return new global::X39.UnitedTacticalForces.WebApp.Api.ResourceClaim.Item.Item.WithResourceIdentifierItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.ResourceClaim.Item.WithResourcePrefixItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithResourcePrefixItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/resource-claim/{resourcePrefix}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.ResourceClaim.Item.WithResourcePrefixItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithResourcePrefixItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/resource-claim/{resourcePrefix}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
