// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using X39.UnitedTacticalForces.WebApp.Api.Events.Item.Slotting.Item.Assign;
using X39.UnitedTacticalForces.WebApp.Api.Events.Item.Slotting.Item.Delete;
using X39.UnitedTacticalForces.WebApp.Api.Events.Item.Slotting.Item.Unassign;
using X39.UnitedTacticalForces.WebApp.Api.Events.Item.Slotting.Item.Update;
namespace X39.UnitedTacticalForces.WebApp.Api.Events.Item.Slotting.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \events\{eventId}\slotting\{slotNumber}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithSlotNumberItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The assign property</summary>
        public global::X39.UnitedTacticalForces.WebApp.Api.Events.Item.Slotting.Item.Assign.AssignRequestBuilder Assign
        {
            get => new global::X39.UnitedTacticalForces.WebApp.Api.Events.Item.Slotting.Item.Assign.AssignRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The deletePath property</summary>
        public global::X39.UnitedTacticalForces.WebApp.Api.Events.Item.Slotting.Item.Delete.DeleteRequestBuilder DeletePath
        {
            get => new global::X39.UnitedTacticalForces.WebApp.Api.Events.Item.Slotting.Item.Delete.DeleteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The unassign property</summary>
        public global::X39.UnitedTacticalForces.WebApp.Api.Events.Item.Slotting.Item.Unassign.UnassignRequestBuilder Unassign
        {
            get => new global::X39.UnitedTacticalForces.WebApp.Api.Events.Item.Slotting.Item.Unassign.UnassignRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The update property</summary>
        public global::X39.UnitedTacticalForces.WebApp.Api.Events.Item.Slotting.Item.Update.UpdateRequestBuilder Update
        {
            get => new global::X39.UnitedTacticalForces.WebApp.Api.Events.Item.Slotting.Item.Update.UpdateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.Events.Item.Slotting.Item.WithSlotNumberItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSlotNumberItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/events/{eventId}/slotting/{slotNumber}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.Events.Item.Slotting.Item.WithSlotNumberItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSlotNumberItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/events/{eventId}/slotting/{slotNumber}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
