// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using X39.UnitedTacticalForces.WebApp.Api.UpdateStream.Subscribe;
namespace X39.UnitedTacticalForces.WebApp.Api.UpdateStream
{
    /// <summary>
    /// Builds and executes requests for operations under \update-stream
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UpdateStreamRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The subscribe property</summary>
        public global::X39.UnitedTacticalForces.WebApp.Api.UpdateStream.Subscribe.SubscribeRequestBuilder Subscribe
        {
            get => new global::X39.UnitedTacticalForces.WebApp.Api.UpdateStream.Subscribe.SubscribeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.UpdateStream.UpdateStreamRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UpdateStreamRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/update-stream", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.UpdateStream.UpdateStreamRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UpdateStreamRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/update-stream", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
