// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using X39.UnitedTacticalForces.WebApp.Api.Models;
namespace X39.UnitedTacticalForces.WebApp.Api.ModPacks.Create.Composition
{
    /// <summary>
    /// Builds and executes requests for operations under \mod-packs\create\composition
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CompositionRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.ModPacks.Create.Composition.CompositionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CompositionRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/mod-packs/create/composition{?modPackRevisionIds*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.ModPacks.Create.Composition.CompositionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CompositionRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/mod-packs/create/composition{?modPackRevisionIds*}", rawUrl)
        {
        }
        /// <returns>A <see cref="global::X39.UnitedTacticalForces.WebApp.Api.Models.PlainModPackDefinitionDto"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::X39.UnitedTacticalForces.WebApp.Api.Models.PlainModPackDefinitionDto?> PostAsync(global::X39.UnitedTacticalForces.WebApp.Api.Models.PlainModPackDefinitionDto body, Action<RequestConfiguration<global::X39.UnitedTacticalForces.WebApp.Api.ModPacks.Create.Composition.CompositionRequestBuilder.CompositionRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::X39.UnitedTacticalForces.WebApp.Api.Models.PlainModPackDefinitionDto> PostAsync(global::X39.UnitedTacticalForces.WebApp.Api.Models.PlainModPackDefinitionDto body, Action<RequestConfiguration<global::X39.UnitedTacticalForces.WebApp.Api.ModPacks.Create.Composition.CompositionRequestBuilder.CompositionRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::X39.UnitedTacticalForces.WebApp.Api.Models.PlainModPackDefinitionDto>(requestInfo, global::X39.UnitedTacticalForces.WebApp.Api.Models.PlainModPackDefinitionDto.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::X39.UnitedTacticalForces.WebApp.Api.Models.PlainModPackDefinitionDto body, Action<RequestConfiguration<global::X39.UnitedTacticalForces.WebApp.Api.ModPacks.Create.Composition.CompositionRequestBuilder.CompositionRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::X39.UnitedTacticalForces.WebApp.Api.Models.PlainModPackDefinitionDto body, Action<RequestConfiguration<global::X39.UnitedTacticalForces.WebApp.Api.ModPacks.Create.Composition.CompositionRequestBuilder.CompositionRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json, text/plain;q=0.9");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::X39.UnitedTacticalForces.WebApp.Api.ModPacks.Create.Composition.CompositionRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::X39.UnitedTacticalForces.WebApp.Api.ModPacks.Create.Composition.CompositionRequestBuilder WithUrl(string rawUrl)
        {
            return new global::X39.UnitedTacticalForces.WebApp.Api.ModPacks.Create.Composition.CompositionRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        #pragma warning disable CS1591
        public partial class CompositionRequestBuilderPostQueryParameters 
        #pragma warning restore CS1591
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("modPackRevisionIds")]
            public long?[]? ModPackRevisionIds { get; set; }
#nullable restore
#else
            [QueryParameter("modPackRevisionIds")]
            public long?[] ModPackRevisionIds { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CompositionRequestBuilderPostRequestConfiguration : RequestConfiguration<global::X39.UnitedTacticalForces.WebApp.Api.ModPacks.Create.Composition.CompositionRequestBuilder.CompositionRequestBuilderPostQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
