// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using X39.UnitedTacticalForces.WebApp.Api.GameServers.All;
using X39.UnitedTacticalForces.WebApp.Api.GameServers.Create;
using X39.UnitedTacticalForces.WebApp.Api.GameServers.Item;
namespace X39.UnitedTacticalForces.WebApp.Api.GameServers
{
    /// <summary>
    /// Builds and executes requests for operations under \game-servers
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GameServersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The all property</summary>
        public global::X39.UnitedTacticalForces.WebApp.Api.GameServers.All.AllRequestBuilder All
        {
            get => new global::X39.UnitedTacticalForces.WebApp.Api.GameServers.All.AllRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The create property</summary>
        public global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Create.CreateRequestBuilder Create
        {
            get => new global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Create.CreateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the X39.UnitedTacticalForces.WebApp.Api.gameServers.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.WithGameServerItemRequestBuilder"/></returns>
        public global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.WithGameServerItemRequestBuilder this[long position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("gameServerId", position);
                return new global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.WithGameServerItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the X39.UnitedTacticalForces.WebApp.Api.gameServers.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.WithGameServerItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.WithGameServerItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("gameServerId", position);
                return new global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.WithGameServerItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.GameServers.GameServersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GameServersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/game-servers", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.GameServers.GameServersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GameServersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/game-servers", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
