// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using X39.UnitedTacticalForces.WebApp.Api.Users.All;
using X39.UnitedTacticalForces.WebApp.Api.Users.Item;
using X39.UnitedTacticalForces.WebApp.Api.Users.Login;
using X39.UnitedTacticalForces.WebApp.Api.Users.Logout;
using X39.UnitedTacticalForces.WebApp.Api.Users.Me;
namespace X39.UnitedTacticalForces.WebApp.Api.Users
{
    /// <summary>
    /// Builds and executes requests for operations under \users
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UsersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The all property</summary>
        public global::X39.UnitedTacticalForces.WebApp.Api.Users.All.AllRequestBuilder All
        {
            get => new global::X39.UnitedTacticalForces.WebApp.Api.Users.All.AllRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The login property</summary>
        public global::X39.UnitedTacticalForces.WebApp.Api.Users.Login.LoginRequestBuilder Login
        {
            get => new global::X39.UnitedTacticalForces.WebApp.Api.Users.Login.LoginRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The logout property</summary>
        public global::X39.UnitedTacticalForces.WebApp.Api.Users.Logout.LogoutRequestBuilder Logout
        {
            get => new global::X39.UnitedTacticalForces.WebApp.Api.Users.Logout.LogoutRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The me property</summary>
        public global::X39.UnitedTacticalForces.WebApp.Api.Users.Me.MeRequestBuilder Me
        {
            get => new global::X39.UnitedTacticalForces.WebApp.Api.Users.Me.MeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the X39.UnitedTacticalForces.WebApp.Api.users.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::X39.UnitedTacticalForces.WebApp.Api.Users.Item.WithUserItemRequestBuilder"/></returns>
        public global::X39.UnitedTacticalForces.WebApp.Api.Users.Item.WithUserItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("userId", position);
                return new global::X39.UnitedTacticalForces.WebApp.Api.Users.Item.WithUserItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the X39.UnitedTacticalForces.WebApp.Api.users.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::X39.UnitedTacticalForces.WebApp.Api.Users.Item.WithUserItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::X39.UnitedTacticalForces.WebApp.Api.Users.Item.WithUserItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("userId", position);
                return new global::X39.UnitedTacticalForces.WebApp.Api.Users.Item.WithUserItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.Users.UsersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UsersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/users", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.Users.UsersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UsersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/users", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
