// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Logs.Clear;
using X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Logs.Count;
using X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Logs.Download;
using X39.UnitedTacticalForces.WebApp.Api.Models;
namespace X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Logs
{
    /// <summary>
    /// Builds and executes requests for operations under \game-servers\{gameServerId}\logs
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LogsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The clear property</summary>
        public global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Logs.Clear.ClearRequestBuilder Clear
        {
            get => new global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Logs.Clear.ClearRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The count property</summary>
        public global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Logs.Count.CountRequestBuilder Count
        {
            get => new global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Logs.Count.CountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The download property</summary>
        public global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Logs.Download.DownloadRequestBuilder Download
        {
            get => new global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Logs.Download.DownloadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Logs.LogsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LogsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/game-servers/{gameServerId}/logs{?descendingByTimeStamp*,referenceTimeStamp*,skip*,take*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Logs.LogsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LogsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/game-servers/{gameServerId}/logs{?descendingByTimeStamp*,referenceTimeStamp*,skip*,take*}", rawUrl)
        {
        }
        /// <returns>A List&lt;global::X39.UnitedTacticalForces.WebApp.Api.Models.PlainGameServerLogDto&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::X39.UnitedTacticalForces.WebApp.Api.Models.PlainGameServerLogDto>?> GetAsync(Action<RequestConfiguration<global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Logs.LogsRequestBuilder.LogsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::X39.UnitedTacticalForces.WebApp.Api.Models.PlainGameServerLogDto>> GetAsync(Action<RequestConfiguration<global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Logs.LogsRequestBuilder.LogsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::X39.UnitedTacticalForces.WebApp.Api.Models.PlainGameServerLogDto>(requestInfo, global::X39.UnitedTacticalForces.WebApp.Api.Models.PlainGameServerLogDto.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Logs.LogsRequestBuilder.LogsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Logs.LogsRequestBuilder.LogsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "text/plain;q=0.9");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Logs.LogsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Logs.LogsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Logs.LogsRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        #pragma warning disable CS1591
        public partial class LogsRequestBuilderGetQueryParameters 
        #pragma warning restore CS1591
        {
            [QueryParameter("descendingByTimeStamp")]
            public bool? DescendingByTimeStamp { get; set; }
            [QueryParameter("referenceTimeStamp")]
            public DateTimeOffset? ReferenceTimeStamp { get; set; }
            [QueryParameter("skip")]
            public int? Skip { get; set; }
            [QueryParameter("take")]
            public int? Take { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class LogsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::X39.UnitedTacticalForces.WebApp.Api.GameServers.Item.Logs.LogsRequestBuilder.LogsRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
